# .travis.yml

language: ruby

rvm:
- 2.6.3

services:
  - postgresql
  - xvfb

addons:
  chrome: stable

before_install:
  - export DISPLAY=:99.0

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node

script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec