# .travis.yml
services:
  - postgresql
before_install:
  - export TZ=Asia/Taipei

language: ruby
rvm:
  - 2.6.3

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
script:
  - bundle exec rails webpacker:compile
  - bundle exec rspec