# .travis.yml

language: ruby

rvm:
- 2.6.3

services:
  - postgresql
  - xvfb

addons:
  chrome: stable

before_install:
  - export DISPLAY=:99.0

before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node

script:
  - bundle exec rails webpacker:compile
  - bundle exec rspec