# .travis.yml

language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
rvm:
- 2.6.3
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install
before_script:
  - bundle exec rake db:create db:test:prepare
script:
  - yarn test
  - bundle exec rspec spec
after_success:
  - bundle exec rake assets:precompile